fdisk -l;
pvcreate /dev/vdb;
pvdisplay /dev/vdb;
vgs;
pvs;
df -h /;
vgextend centos /dev/vdb;
lvextend -L +39G /dev/mapper/centos-root;
df -hT /;
xfs_growfs /dev/mapper/centos-root;
yum install wget -y;
yum install unzip -y;
wget -O /etc/yum.repos.d/pbiso.repo https://repo.pbis.beyondtrust.com/yum/pbiso.repo;
yum install pbis-open -y;
hostnamectl set-hostname ets-$RANDOM-$RANDOM;
/opt/pbis/bin/domainjoin-cli join sdlproducts.com cmnambi Csdm@Nov2020;
wget ftp://ktiwari:VQxyE+q7@languageweaver.exavault.com/SDL%20ETS/Application/8.4.x/Latest%20Version/SDL_MTEdge_8_4_5_linux64_installer.zip;
unzip SDL_MTEdge_8_4_5_linux64_installer.zip;
./SDL_MTEdge_8_4_5_linux64_installer/setup-linux-x64.run --mode unattended --prefix /opt/sdl/ets --install_mode master --admin_user_username admin@localhost --admin_user_display_name Admin --admin_user_password 123456 --tls_mode disabled;
wget "ftp://ktiwari:VQxyE+q7@languageweaver.exavault.com/SDL%20ETS/Language%20Pairs/Neural%20MT%20(NMT)/8.5.x/Greek_to_English_Generic_NMT/SDL_ETS_GreEng_Generic_SRV_TNMV_8_5_x_0_installer.zip";
unzip SDL_ETS_GreEng_Generic_SRV_TNMV_8_5_x_0_installer.zip;
./SDL_ETS_GreEng_Generic_SRV_TNMV_8_5_x_0_installer/setup-linux-x64.run --mode unattended;