name: BUILDDEVTEST-1

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  BUILD_SCRIPT:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Run script on the VM
        run: |
          sshpass -p "CmCICD#2024#" ssh -o StrictHostKeyChecking=no ubuntu@13.51.7.24 <<EOF
            source ~/.bashrc
            cd ~/projects/script_test/javaproject/Spring-Boot-main
            which mvn
            mvn -version
            mvn clean
            mvn install 
          EOF
