        name: DR_CICD

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
# No SonarQube configuration found for this project type.

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "CmCICD#2024#" ssh -p 222 -o StrictHostKeyChecking=no ubuntu@13.51.7.24 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main
                              sudo mvn clean
                              sudo mvn install 
                   EOF