        name: MyRelease

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- DOCKER
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: ${{ vars.DOCKER_USERNAME }}
                 password: ${{ vars.DOCKER_ACCESSTOKEN }}
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cicd_dev:main
#------------------JUNIT
          JUNIT:
           needs: [DOCKERHUB]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JUNIT job"
#------------------SELENIUM
          SELENIUM:
           needs: [JUNIT]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an SELENIUM job"
#------------------JMETER
          JMETER:
           needs: [SELENIUM]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JMETER job"

    #---------------- SONARQUBE
          SONARQUBE:
            needs: [JMETER]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: ${{ secrets.SONARQUBE_ACCESSTOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "ClearC0de20S4" ssh -o StrictHostKeyChecking=no root@158.220.107.63 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main
                              mvn clean
                              mvn install 
                   EOF
 
    #---------------- APPROVAL_WORKFLOW
          APPROVAL_WORKFLOW:
            needs: [BUILD_SCRIPT]
            runs-on: ubuntu-latest
            permissions:
               issues: write
            steps:
               - uses: trstringer/manual-approval@v1
                 with:
                   secret: ${{ secrets.GITHUB_TOKEN }}
                   approvers: DevTester2025
                   issue-title: "Manual Approval"
                   issue-body: "run_id: ${{ github.run_id }}"
 
    #---------------- ORCHESTRATION
          ORCHESTRATION:
            needs: [APPROVAL_WORKFLOW]
            runs-on: ubuntu-latest
            permissions:
               issues: write
            steps:
               - uses: trstringer/manual-approval@v1
                 with:
                   secret: ${{ secrets.GITHUB_TOKEN }}
                   approvers: DevTester2025
                   issue-title: "Orchestration"
                   issue-body: "run_id: ${{ github.run_id }}"