        name: sample_docker_test_10

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- DOCKER
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           environment:
              name: PRODUCTION
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: opsmasteradmin
                 password: ${{ vars.DOCKER_ACCESSTOKEN_OPS }}
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: opsmasteradmin/cloudmatiq:main
            

      #---------------- VIRTUAL_MACHINE
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            environment:
              name: PRODUCTION
            needs: [DOCKERHUB]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3
               - name: Deploy to Linux Server
                 run: |
                     sshpass -p CmCICD#2024# ssh -o StrictHostKeyChecking=no ubuntu@13.51.7.24 "sudo docker pull opsmasteradmin/cloudmatiq:main && sudo docker run --rm -p 80:80 -d opsmasteradmin/cloudmatiq:main"