        name: TEST-DEMO4

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- DOCKER
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: devtester2025
                 password: dckr_pat_W9cx0PiYuv_5BgW54h7oBv1viCU
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: devtester2025/undefined:main
            
#------------------JUNIT
          JUNIT:
           needs: [DOCKERHUB]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JUNIT job"
#------------------JMETER
          JMETER:
           needs: [JUNIT]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JMETER job"

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [JMETER]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "ClearC0de20S4" ssh -o StrictHostKeyChecking=no root@158.220.107.63 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main
                              mvn clean
                              mvn install 
                   EOF